version: '3.5'

services:
  backend:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    volumes:
      - .:/backend
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: database_name
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
    entrypoint: ["bash", "./backend/backend_entrypoint.sh"]
    

  db:
    # We use the predefined Postgres image
    image: postgres:11.1
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '.:/frontend/node_modules'
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    entrypoint: ["bash","./frontend/frontend_entrypoint.sh"]
    depends_on:
      - db
      - backend
# Define the volumes
volumes:
  pgdata: